/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package it.unibo.wenvusage;

import org.checkerframework.dataflow.qual.TerminatesExecution;
import org.junit.After;
import org.junit.Before;
import org.junit.Test;

import static org.junit.Assert.*;

public class AppTest {

    @Before
    public void setup() {
        System.out.println("setup");
    }

    @After
    public void after() {
        System.out.println("after the setup and other test :)");
    }

    @Test
    public void testAppHasAGreeting() {
        System.out.println("testAppHasAGreeting");
        App classUnderTest = new App();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }

    @Test
    public void other_test() {
        System.out.println("other_test");
//        fail();
        assertTrue(true);
    }

    @Test
    public void other_test_2() {
        System.out.println("other_test_2");
        assertTrue(2 == 2);
    }

}
